version: '3'

vars:
  BINARY_NAME: '{{if eq OS "windows"}}quell.exe{{else}}quell{{end}}'

tasks:
  default:
    cmds:
      - task: run

  run:
    desc: 直接编译并运行代码
    cmds:
      - go build -o quell.exe ./cmd/quell && ./quell.exe

  build:
    desc: 编译生成二进制文件到 bin 目录
    cmds:
      - cmd: echo "Building {{.BINARY_NAME}}..."
      - cmd: go build -o bin/{{.BINARY_NAME}} ./cmd/quell/main.go
      - cmd: echo "Build success! Output! bin/{{.BINARY_NAME}}"

  exec:
    desc: 直接运行 bin 目录下的 exe (需先 build)
    deps: [build]
    cmds:
      - powershell -Command "./bin/{{.BINARY_NAME}}"

  clean:
    desc: 删除构建产物
    cmds:
      - cmd: rm -rf bin/
      - cmd: echo "Cleaned."
    ignore_error: true